first commit
XOLP/sprint_six pull request #1
Opened 2024-10-24 15:20 UTC by XOLP

2024-10-24 20:36 UTC, dirtymew requested changes
Привет Глеб

по работе есть замечания - нужно поправить

2024-10-24 20:36 UTC, dirtymew commented on precode.go
> +	res.Write(respon)
_ , _ = w.Write(resp)
тут стоит либо явно проигнорировать ошибку или ее логировать

2024-10-24 20:36 UTC, dirtymew commented on precode.go
> +	idd := chi.URLParam(req, "idd")
/tasks/{id} - параметр  id а не `idd`

2024-10-24 20:36 UTC, dirtymew commented on precode.go
> +	idd := chi.URLParam(req, "idd")
id

2024-10-24 20:36 UTC, dirtymew commented on precode.go
> +	tasks[task.ID] = task
тут нужно проверить что такой задачи нет в tasks и если есть вернуть ошибку

2024-10-25 10:51 UTC, XOLP commented
Поправил по всем пунктам

2024-10-25 22:09 UTC, dirtymew approved these changes
Привет Глеб

задание принимаю - но обрати внимание на комментарии - есть замечания по правкам

2024-10-25 22:09 UTC, dirtymew commented on precode.go
> +		http.Error(res, err.Error(), http.StatusBadRequest)
тут это делать уже бесполезно если ошибка из  Write - лучше просто залогировать

2024-10-25 22:09 UTC, dirtymew commented on precode.go
> +	for _, ts := range tasks {
тут не эффективно - доступ по ключу в мапе в среднем O(1) - обход в по ней O(n)

```
if _, ok := tasks[id]; ok {
   http.Error(res, "already exist", http.StatusBadRequest)
}
```

2024-11-15 08:29 UTC, merged